
project_id = "xykomxyyxgcztgmhqzvm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions]
[functions.chat]
verify_jwt = false

[functions.get-draft-data]
verify_jwt = false

[functions.vector-operations]
verify_jwt = false
